spring.application.name=application
spring.datasource.url=jdbc:postgresql://localhost:5432/HumanResourceManagement
spring.datasource.username=postgres
spring.datasource.password=Mesi@Tade0313
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#eurika.client.enabled=false
#springdoc.api-docs.path=/v3/api-docs
springdoc.api-docs.enabled=true
#springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.swagger-ui.syntax-highlight.theme=monokai
#springdoc.swagger-ui.doc-expansion=list
springdoc.packages-to-scan=com.HumanResourceManagement.application
#springdoc.paths-to-match=/**
springdoc.show-actuator=false
