spring.application.name=application
spring.datasource.url=jdbc:postgresql://localhost:5432/HumanResourceManagement
spring.datasource.username=postgres
spring.datasource.password=Mesi@Tade0313
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#eurika.client.enabled=false