spring.application.name=application
spring.config.import=optional:file:${user.dir}/.env[.properties]
spring.datasource.url=${SUPABASE_DB_URL}
spring.datasource.username=${SUPABASE_DB_USERNAME}
spring.datasource.password=${SUPABASE_DB_PASSWORD}
spring.datasource.hikari.data-source-properties.sslmode=require
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#eurika.client.enabled=false
#springdoc.api-docs.path=/v3/api-docs
springdoc.api-docs.enabled=true
#springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.swagger-ui.syntax-highlight.theme=monokai
#springdoc.swagger-ui.doc-expansion=list
springdoc.packages-to-scan=com.HumanResourceManagement.application
#springdoc.paths-to-match=/**
springdoc.show-actuator=false
